# Generated by Django 5.1.4 on 2025-01-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_coursepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=100, verbose_name='Цена в долларах'),
        ),
    ]
